CREATE SCHEMA IF NOT EXISTS Users;

DROP TABLE Users.User;

CREATE TABLE IF NOT EXISTS Users.USER (
    ID SERIAL NOT NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    MIDDLENAME VARCHAR(255),
    USERLOGIN VARCHAR(36) NOT NULL,
    ISBLOCKED BOOLEAN NOT NULL DEFAULT FALSE,
    USERPASSWORD VARCHAR(512) NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (ID)
);